# Generated by Django 2.2.12 on 2020-07-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webScraper', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='offre',
            constraint=models.UniqueConstraint(fields=('job_link',), name='unique job posting'),
        ),
    ]
