# Generated by Django 2.2.12 on 2020-07-14 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webScraper', '0002_auto_20200713_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
