# Generated by Django 2.2.12 on 2020-07-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webScraper', '0003_offre_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='jobboard',
            field=models.CharField(default='null for now', max_length=200),
        ),
    ]
